# Install dependencies only when needed
FROM node:22-alpine AS deps
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY ./dist/apps/rahat-community/package.json ./
RUN npm install -g pnpm@10.12.1 && pnpm install

FROM node:22-alpine AS builder
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY ./dist/apps/rahat-community/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npm install -g pnpm@10.12.1 && pnpm prisma generate
CMD [ "node", "main.js" ]
