# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/rahat-community/package.json ./
RUN npm install -g pnpm && pnpm install

FROM node:18-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/rahat-community/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npm install -g pnpm && pnpm prisma generate
CMD [ "node", "main.js" ]