# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/frontend/package.json .npmrc ./
RUN yarn install --production && yarn cache clean


FROM node:18-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/frontend/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
CMD [ "yarn", "start" ]