name: Main CI/CD
on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

env:
  CI: false
  # env_main: ${{ secrets.ENV_MAIN }}

jobs:
  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      # - name: create environment file
      #   run: |
      #     touch ./.env && echo "$env_main" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push web
        id: build-push-web
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: esatya/community-api:main

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .   